services:
  web:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "3000:3000"
    networks:
      - my_network
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - my_network

  # Add more containers below (nginx, postgres, etc.)

# containers to communicate
# resolve container_name as hostname
networks:
  my_network:
    name: my_network
    external: true
